name: Build FPC Win64 Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Quellcode auschecken
      uses: actions/checkout@v3

    - name: Free Pascal Win64 herunterladen und entpacken
      shell: cmd
      run: |
        echo create .\fpc
        mkdir fpc
        cd fpc
        echo download archive...
        curl -LO https://kallup.net/win32/packed.zip
        echo extract archive---
        7z x packed.zip
        dir

    - name: PATH für Compiler und Tools setzen
      shell: cmd
      run: |
        echo "%GITHUB_WORKSPACE%\fpc" >> %GITHUB_PATH%

    - name: Build-Batch-Datei ausführen
      shell: cmd
      run: |
        cd src
        ..\fpc\ppcrossx64.exe -dDLLEXPORT -dLANGDEU -dDLLDEBUG -n -B -Twin64 -FE. -Fu. -O3 -Os RTLLib.pas
        ..\fpc\ppcrossx64.exe -dDLLIMPORT -dLANGDEU -dDLLDEBUG -n -B -Twin64 -FE. -Fu. -O3 -Os test.pas
        ..\fpc\x86_64-win64-strip.exe test.exe
        ..\fpc\x86_64-win64-strip.exe rtllib.dll
        ..\fpc\ppcrossx64.exe -dDLLIMPORT -dLANGDEU -dDLLDEBUG -n -B -Twin64 -FE. -Fu. -O3 -Os parser.pas
        ..\fpc\x86_64-win64-strip.exe parser.exe

    - name: Build-Output in ZIP packen
      shell: cmd
      run: |
        mkdir dist
        copy src\*.exe dist\
        copy src\*.dll dist\
        powershell -Command "Compress-Archive -Path dist\* -DestinationPath fpc_build_output.zip"

    - name: ZIP als Artefakt bereitstellen
      uses: actions/upload-artifact@v4
      with:
        name: fpc-binaries
        path: fpc_build_output.zip
