# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PythonObserver
run-name: ${{ github.actor }} Python Observer RC-1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  Run-Windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      shell: pwsh
      run: |
        $env:MY_WORK_DIR = "${{ github.workspace }}"
        D:
        cd $env:MY_WORK_DIR\\src
        $pythonExe  = Get-Command python -ErrorAction Ignore
        $installExe = Get-Command pyinstaller -ErrorAction Ignore
        if ($pythonExe) {
          Write-Output "Python is installed."
          python3 --version
        } else {
          Write-Output "Python is not installed, try to install it..."
          python -m pip install --upgrade pip
          pip install flake8 pytest
          python3 -m pip install pysqlite3
          python3 -m pip install PyQt5
          python3 -m pip install PyQt5-sip
          python3 -m pip install PyQtWebEngine
        }
        if ($pyInstallerExe) {
          Write-Output "pyInstaller is installed."
          pyinstaller --version
        } else {
          pip install pyinstaller
          pip install --upgrade pyinstaller
        }
        Write-Output "Create ByteCode ..."
        python3 -m compileall observer.py
        Write-Output "Create Application ..."
        $pyInstallerArgs = "pyInstaller --noconfirm --onefile --console      " +
        "--icon         $env:MY_WORK_DIR\src\img\floppy-disk.ico " +
        "--splash       $env:MY_WORK_DIR\src\img\splash.png      " +
        "--version-file $env:MY_WORK_DIR\src\version.info        " +
        "--add-data     $env:MY_WORK_DIR\src\LICENSE;.           " +
        "--add-data     $env:MY_WORK_DIR\src\locales;locales\    " +
        "--add-data     $env:MY_WORK_DIR\src\img;img\            " +
        "               $env:MY_WORK_DIR\src\observer.py"
        $pyInstallerArgs

  Run-Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python3 -m pip install pysqlite3 
        python3 -m pip install PyQt5
        python3 -m pip install PyQt5-sip
        python3 -m pip install PyQtWebEngine
        
