# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PythonObserver
run-name: ${{ github.actor }} Python Observer RC-1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  Run-Windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python3 -m pip install pysqlite3
        python3 -m pip install PyQt5
        python3 -m pip install PyQt5-sip
        python3 -m pip install PyQtWebEngine
    - name: Start Python in PowerShell
      shell: pwsh
      run: |
        $env:MY_WORK_DIR = "${{ github.workspace }}"
        python3 --version
        python3 -c "print('Hello World !')"
        Write-Output "Hallo Variable: $env:MY_WORK_DIR, ${{ github.workspace }}"
        python3 -m compileall observer.py

  Run-Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python3 -m pip install pysqlite3 
        python3 -m pip install PyQt5
        python3 -m pip install PyQt5-sip
        python3 -m pip install PyQtWebEngine
        
